import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/navbar";
import Sukhumvit from "./assets/Sukhumvit";
import { lusitana, inter } from "@/app/ui/fonts";

const sukhumvit = Sukhumvit;
export const metadata: Metadata = {
  title: "EZ-Room",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
