import "./globals.css";
import type { Metadata } from "next";
import Sukhumvit from "./assets/Sukhumvit";

const sukhumvit = Sukhumvit;
export const metadata: Metadata = {
  title: "EZ-Room",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${sukhumvit.variable}`}>{children}</body>
    </html>
  );
}
