import './globals.css'
import type { Metadata } from 'next'

import localFont from 'next/font/local'

const sukhumvit = localFont({
  src : [{
    path : './fonts/Sukhumvit/SukhumvitSet-Text.ttf',
    weight : '400'
  },
  {
    path : './fonts/Sukhumvit/SukhumvitSet-Bold.ttf',
    weight : '700'
  },
  {
    path : './fonts/Sukhumvit/SukhumvitSet-Light.ttf',
    weight : '300'
  },
  {
    path : './fonts/Sukhumvit/SukhumvitSet-Medium.ttf',
    weight : '500'
  },
  {
    path : './fonts/Sukhumvit/SukhumvitSet-SemiBold.ttf',
    weight : '600'
  },
  {
    path : './fonts/Sukhumvit/SukhumvitSet-Thin.ttf',
    weight : '100'
  },
],
  display : 'swap',
})


export const metadata: Metadata = {
  title: 'EZ-Room',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sukhumvit.className}>{children}</body>
    </html>
  )
}
